
name: 'MyZVLoadingSecrets'
description: 'Test'
author: 'zv'
branding:
  icon: lock
  color: blue
inputs:
  secretName:
    description: 'name of the secret'
    required: true



runs:
  using: "composite"
  steps:
    - name: actions checkout
      uses: actions/checkout@v4.1.5
      with:
        repository: naveennv2k/Loadingsecrets  # Replace with the owner and repository name
        ref: main
         
    - name: install cli
      run: unzip zv_cli.zip
      shell: bash
    - name: run program
      run: node ./dist/index.js ${{inputs.secretName}}
      shell: bash
    
    - name: export secret
      id: export-secret
      run: |
           echo "username=$secretUsername" >> $GITHUB_OUTPUT
           echo "password=$ " >> $GITHUB_OUTPUT 
       
      shell: bash
      
