
name: 'MyZVLoadingSecrets'
description: 'Test'
author: 'zv'
branding:
  icon: lock
  color: blue




runs:
  using: "composite"
  steps:
   
         
    
    - name: run program
      run: |
           cd  GITHUB_ACTION_PATH
           node ./dist/index.js ${{inputs.secretName}}
      shell: bash
    
    - name: export secret
      id: export-secret
      run: |
           echo "username=$secretUsername" >> $GITHUB_OUTPUT
           echo "password=$ " >> $GITHUB_OUTPUT 
       
      shell: bash
    - name: actions checkout
      uses: actions/checkout@v4.1.5  
      
