
name: 'My Custom Action'
description: 'Test'
author: 'zv'
inputs:
  secretname:
    description: 'name of the secret'
    required: true
outputs:
  secretname:
    value: ${{ steps.export-secret.outputs.username }} 
  secretPassword:
    value: ${{steps.export-secret.outputs.password}}     


# runs:
#   using: 'node20'
#   main: 'dist/index.js'
runs:
  using: "composite"
  steps:
    - name: actions checkout
      uses: actions/checkout@v4.1.5
      with:
        repository: naveennv2k/Loadingsecrets  # Replace with the owner and repository name
        ref: main
    - name: list
      run: ls -a     
    - name: install cli
      run: unzip zv_cli.zip
      shell: bash
    - name: run program
      run: node ./dist/index.js 
      shell: bash
    
    - name: export secret
      id: export-secret
      run: |
           echo "username=$secretUsername" >> $GITHUB_OUTPUT
           echo "password=$secretPassword" >> $GITHUB_OUTPUT 
       
      shell: bash
      
