name: Say Hello

on: [workflow_call]

jobs:
  run-my-action:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - name: actions checkout
        uses: actions/checkout@v4.1.5
        with:
          repository: naveennv2k/Loadingsecrets
      - id: getSecrets
        uses: ./
      - name: getSecrets
        run: echo "$username"
